from .data import DataDeleteView
from .data import DataUpdateView
from .data import DataDetailView
from .data import DataCreateView
from .data import DataListView
from .capteur import CapteurDeleteView
from .capteur import CapteurUpdateView
from .capteur import CapteurDetailView
from .capteur import CapteurCreateView
from .capteur import CapteurListView
from .views import *