from .data import DataDeleteTestCase
from .data import DataUpdateTestCase
from .data import DataDetailTestCase
from .data import DataCreateTestCase
from .data import DataListTestCase
from .capteur import CapteurDeleteTestCase
from .capteur import CapteurUpdateTestCase
from .capteur import CapteurDetailTestCase
from .capteur import CapteurCreateTestCase
from .capteur import CapteurListTestCase
